bearmq:
  username: gkxockzmeyjhuoodczbyriogw
  password: hZyrEkooaaHamNMWuKGHARNPN
  host: localhost
  port: 6667
  virtual-host: nuricanozturk-jsquewyboyhlfoobdiqltqber
  api-key: bearmqt-vRvkJYiEtgYWHYxwZdzAcRFmxNTrpgwRpNRniExYcaof
logging:
  level:
    root: warn