server:
  port: 5555
app:
  exchange: exchangeB
  queue: queueY
  queue2: queueZ

bearmq:
  username: gkxockzmeyjhuoodczbyriogw
  password: hZyrEkooaaHamNMWuKGHARNPN
  host: localhost
  port: 6667
  virtual-host: nuricanozturk-jsquewyboyhlfoobdiqltqber
  api-key: bearmqt-vRvkJYiEtgYWHYxwZdzAcRFmxNTrpgwRpNRniExYcaof
  listener:
    initial-delay-ms: 200
    period-ms: 350