server:
  port: 2222
app:
  exchange: exchangeA
  queue: queueZ
  queuet: queueT


bearmq:
  username: gkxockzmeyjhuoodczbyriogw
  password: hZyrEkooaaHamNMWuKGHARNPN
  host: localhost
  port: 6667
  virtual-host: nuricanozturk-jsquewyboyhlfoobdiqltqber
  api-key: bearmqt-vRvkJYiEtgYWHYxwZdzAcRFmxNTrpgwRpNRniExYcaof
